### ISSUE TITLE
Create testing config sample

### ISSUE THREAD

**Issue by foxycode** [mrtnzlml/testbench#13]
I didn't figured out how to configure database to run all testbench tests (I am talking about contributing to this repository). Also I got this error in some cases:

```
E_NOTICE: session_start(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13)
```

Maybe directing session dir to testdir should help.

**Comment by mrtnzlml** [comment]
You do not have to setup database to use Testbench. You have to setup database only if you want to use `Testbench\TDoctrine` trait. This setup doesn't depend on Testbench. You should use `doctrine:` config section as you probably already know (classic `config.local.neon`).

Can you please investigate more about mentioned notice? I don't know how to reproduce this error. Also I am not sure if it's problem in Testbench...

**Comment by foxycode** [comment]
@mrtnzlml Yes, but I am talking about testing testbench. I want to know how to configure datbase in `testbench/tests/tests.neon`.

session_start error is related to php config. I wasn't able to find out more. What I know is, that in my previous presenter testing solution I created my own UserStorage which does not work with session to be able fully test restricted presenters. Sessions in console are always problem, session_start should not be called at all.

**Comment by mrtnzlml** [comment]
``` neon
doctrine:
    driver: pdo_mysql #or pdo_pgsql
    user: root
    password: '...'
```

As you can see it's common Doctrine configuration. Testbench itself doesn't need database so it's good enough to connect to the empty database. It uses this database only for the first connection and according to the setting `testbench:sqls:` it creates another clear databases and uses them. You can see Testbench project setting in [.travis.yml file](https://github.com/mrtnzlml/testbench/blob/master/.travis.yml#L24-L31).

**Comment by mrtnzlml** [comment]
Fixed in https://github.com/mrtnzlml/testbench/commit/1345eeb9719d3b768660d16625d8d83b9d0cfd58. About session problem. [Tests in Travis CI](https://travis-ci.org/mrtnzlml/testbench) are fine and I cannot solve problem that doesn't exist. If there is still problem with sessions please open new issue and try to provide more information. Anyway thanks for reporting.
