### ISSUE TITLE
Problém s @dataProviderom

### ISSUE THREAD

**Issue by camohub** [mrtnzlml/testbench#17]
Zdravím,
mám menší problém s @dataProviderom. Testujem formulár s jedným políčkom, ktoré je required. Urobil som test, kde by raz mal required prejsť a raz nie. Keď to testujem tak dostanem vždy rovnaký výsledok. Vždy ten, čo je prvý v @dataProvidery. 

``` php
public function commentFormParameters()
{
    return [
        [ [ 'test' => 1, 'content' => '', 'do' => 'commentForm-submit' ] ],
        [ [ 'test' => 2, 'content' => 'Some required content.', 'do' => 'commentForm-submit' ] ],
    ];
}
```

Teda prvý test by nemal prejsť a druhý áno. Ale getErrors() vracia vždy, výsledok prvého testu a nereaguje na zmenu $post prametrov.
Celý test vyzerá takto:

``` php
/**
 * @dataProvider commentFormParameters
 * @param $post
 */
public function testCommentForm( $post )
{
    $response = $this->check( 'Articles:show', [ 'title' => 'ako-islo-vajce-na-vandrovku' ], $post );
    $errors = $this->getPresenter()->getComponent( 'commentForm' )->getErrors();

    Assert::true( count( $errors ) > 0 );
    Debugger::log( $errors );
}
```

Ako to vyriešim?
Podľa všetkého s to týka podmienky v metóde check()

``` php
if (!$this->__testbench_presenter) .... 
```

Takže vlastne by malo stačiť priradiť NULL?

``` php
$this->__testbench_presenter = NULL;
```

**Comment by mrtnzlml** [comment]
Nejsem si jist, jestli je to bug a jak to dobře opravit. Takto totiž formuláře nejde použít, nejde odeslat v jednom requestu formulář 2x. Myslím si, že by stejně bylo lepší rozdělit tento jeden test na 2 menší a otestovat tyto funkce zvlášť. Toto řešení se ti nelíbí?

**Comment by camohub** [comment]
No lenže takto ako to je to nieje kompatibilné s Testerom. Pretože @dataProvider by mal poskytovať práve možnosť vytvoriť cyklus requestov s rôznymi parametrami. Teda nie jeden request.

**Comment by camohub** [comment]
Aspoň tak to ja chápem.   A tak to mám aj napísané. Od validácie až po redirect. Akurát bez TestBenchu, každý request inštancujem znova.

**Comment by mrtnzlml** [comment]
Tak by to mělo být vyřešeno ve verzi v2.1.2 a už není potřeba používat ten workaround.
