### ISSUE TITLE
Nelze získat uživatele z mocku presenteru

### ISSUE THREAD

**Issue by adaamz** [mrtnzlml/testbench#26]
Má fungovat v dataProvideru `$this->getPresenter()->getUser()->isAllowed(...)` nebo je to jen můj naivní požadavek? :-)
Dělám takovej ultimátní test, kterej projde všechny presentery a zavolá všechny akce, které nemají žádný povinný parametr. No a když jdu na zakázanou akci/presenter pro danou roli tak mě to přesměruje na 403 stránku což neprojde testem na TextResponse atd.
Nebo je jiný způsob jak vyřešit tu autorizaci?

Ještě doplním, že už `$this->getPresenter()` nevrátí presenter, protože se vkládá až při checkování.

**Comment by mrtnzlml** [comment]
Je důležité uvědomit si (což jsi asi udělal), že nemůžeš mít k dispozici presenter, dokud ho neotestuješ. Ten presenter se jinak nevytváří a to čistě z důvodu rychlosti. Proto je možno udělat toto:

``` php
public function testRender()
{
    $this->checkAction('Presenter:');
    Assert::type(\Nette\Security\User::class, $this->getPresenter()->getUser()); //Presenter:
}
```

Ale špatně toto (obrácené pořadí):

``` php
public function testRender()
{
    Assert::type(\Nette\Security\User::class, $this->getPresenter()->getUser()); //jaký presenter?
    $this->checkAction('Presenter:');
}
```

Asi by nebyl problém dodělat podporu pro něco jako `getPresenter($destination = NULL)`, takže bys mohl předat název a on by se ten presenter vytvořil pokud není. To teď ale Testbench neumí, protože to zatím nikdo nepotřeboval.

Druhá (a podle mého lepší) varianta jak získat uživatele je použít `Testbench\TCompiledContainer`:

``` php
use \Testbench\TCompiledContainer;

public function testRender()
{
    //netřeba řešit presenter, když chci vlastně jen uživatele
    Assert::type(\Nette\Security\User::class, $this->getService(\Nette\Security\User::class));
}
```

Případně jako inspirace ještě jeden způsob: https://github.com/mrtnzlml/testbench/blob/master/tests/Traits/TPresenterTest.phpt#L110-L158

Jak vidíš, Testbench se nesnaží dělat nic zázračného. Smyslem je dělat jen minimum základních (a pro programátora otravných) operací a hlavně nikterak zásadně neměnit způsob práce, který mají všichni naučený z Nette. Jen má určitá specifika, která podléhají optimalizaci pro rychlost... :)

Pokud jsem dostatečně zodpověděl tvůj dotaz, tak tuto issue prosím zavři.

**Comment by adaamz** [comment]
No jasně, já se přihlašuju v setUp` metodě a tam vlastně toho uživatele dostanu :-)
Díky

Hm, tak prej se volá test -> dataprovider a potom až setup, takže toho uživatele dostanu pozdě.
Nějakej nápad?

**Comment by mrtnzlml** [comment]
Nerozumím otázce. Setup se volá [vždy před testem](https://github.com/nette/tester/blob/b5cf866a73eece24fa290bcc68b29b5c520cdd47/tests/Framework/TestCase.order.phpt#L37-L42) a dataprovider se volá před [testovací metodou](https://github.com/nette/tester/blob/b5cf866a73eece24fa290bcc68b29b5c520cdd47/tests/Framework/TestCase.dataProvider.phpt#L68). Jak je to ve spojení se setup metodou si z hlavy netroufnu říct, ale tak či tak je volána jako první. Pokud máš nějaký problém s Testerem jako takovým, tak bude možná lepší zeptat se na fóru?

Nebo pokud je nějaký fail v Testbench knihovně, tak prosím pošli [minimální kód](https://github.com/mrtnzlml/testbench/blob/master/tests/Issues/Issue_20.phpt), abych jej zreprodukoval.

**Comment by adaamz** [comment]
ok, je to chyba/feature v testeru - volá se dataProvider, potom až setup atd.
