### ISSUE TITLE
Typo in TestbenchExtension? + Databse behavior proposal

### ISSUE THREAD

**Issue by xklid101** [mrtnzlml/testbench#37]
_Typo:_
Looks like you have a typo here https://github.com/mrtnzlml/testbench/blob/master/src/TestbenchExtension.php#L80
There should be `$sectionConfig` instead of `$extensionConfig`, I guess...

_Database:_
I am using persistent databases for testing, but Testbench still creates and drops new database for every test. Some config option for such behavior would be nice...

**Comment by mrtnzlml** [comment]
Related PR: https://github.com/mrtnzlml/testbench/pull/38

**Comment by mrtnzlml** [comment]
Thanks for reporting - fixed by [this commit](https://github.com/mrtnzlml/testbench/commit/7a546e1f8846567eb2b6b154cba67003e39de45a). In `dev-master` there is also support for shared databases.
