### ISSUE TITLE
PHP 7.2 Nette\Object

### ISSUE THREAD

**Issue by Machacek76** [mrtnzlml/testbench#52]
I have this error
`Exception: Replace deprecated Nette\Object with trait Nette\SmartObject in /var/www/cms/vendor/mrtnzlml/testbench/src/ContainerFactory.php:8`

Is good solution, remove extends from class ContainerFactory?

PHP 7.2.5-1+ubuntu18.04.1
Nette 2.4

**Comment by f3l1x** [comment]
Thanks for an issue. I will fix it.

**Comment by konecnyjakub** [comment]
This is already fixed on master - aa056ba1. There was just no release after the fix.

**Comment by Machacek76** [comment]
Thanks it works

**Comment by f3l1x** [comment]
New version released 2.5.0
